# Generated by Django 6.0.6 on 2026-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('oab', models.CharField(max_length=50)),
                ('formacao', models.TextField(help_text='Resumo da graduação, mestrado, etc.')),
                ('cursos', models.TextField(blank=True, help_text='Outros cursos e certificações')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Direito Empresarial', max_length=150)),
                ('especificidades', models.TextField(help_text='Detalhes dos serviços prestados nesta área')),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
            },
        ),
        migrations.CreateModel(
            name='InformacoesEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, help_text='Sala, bloco, andar...', max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(help_text='Ex: RJ, SP, MG', max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('x_twitter', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Informação do Escritório',
                'verbose_name_plural': 'Informações do Escritório',
            },
        ),
        migrations.CreateModel(
            name='SecaoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ex: historia_escritorio, missao, visao', max_length=100, unique=True)),
                ('titulo', models.CharField(blank=True, help_text='Título que aparecerá na tela', max_length=200)),
                ('conteudo', models.TextField(help_text='O texto completo da seção')),
            ],
            options={
                'verbose_name': 'Seção de Texto',
                'verbose_name_plural': 'Seções de Texto',
            },
        ),
    ]
