# Generated by Django 6.0.6 on 2026-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='email_profissional',
            field=models.EmailField(blank=True, help_text='E-mail direto do advogado', max_length=254),
        ),
        migrations.AddField(
            model_name='advogado',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profissional'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Perfil do LinkedIn'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='telefone_fixo',
            field=models.CharField(blank=True, help_text='Telefone da sala ou ramal', max_length=20),
        ),
    ]
