# Generated by Django 6.0.6 on 2026-06-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_advogado_email_profissional_advogado_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto profissional de rosto (idealmente quadrada)', null=True, upload_to='equipe/'),
        ),
        migrations.AddField(
            model_name='informacoesescritorio',
            name='foto_local',
            field=models.ImageField(blank=True, help_text='Foto da fachada, recepção ou paisagem clássica do Rio de Janeiro', null=True, upload_to='escritorio/'),
        ),
        migrations.AddField(
            model_name='secaotexto',
            name='imagem_destaque',
            field=models.ImageField(blank=True, help_text='Foto ilustrativa para acompanhar o texto (opcional)', null=True, upload_to='textos/'),
        ),
    ]
