# Generated by Django 6.0.6 on 2026-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_advogado_foto_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_destino', models.CharField(choices=[('home', 'Página Inicial (Home)'), ('sobre', 'Página Sobre Nós'), ('contato', 'Página de Contato')], help_text='Em qual página esta foto deve aparecer?', max_length=20)),
                ('imagem', models.ImageField(upload_to='site_geral/')),
                ('descricao', models.CharField(help_text="Descrição curta da imagem para acessibilidade (ex: 'Fachada do prédio')", max_length=150)),
            ],
        ),
    ]
