# Generated by Django 6.0.6 on 2026-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_imagemsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoLei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
            ],
        ),
    ]
